sudo: false
language: node_js
node_js:
- 4.2.4
script:
- npm install -g bower && npm install -g vulcanize && bower install && ./build.sh
- cd gem && ./bin/setup && bundle exec rake
deploy:
  provider: rubygems
  skip_cleanup: true
  api_key:
    secure: "ofwqmMBzUHm7cr4ANGK0aDDXrPxy6eDU4btEzWKDlhm9LAXiAqOBU7uj95tK+PFvXmgsbhYrZE9At0CDcK0OBQn8/9wud++JyXB4oAzU5bgpY7oDghh02XowQy9EV1hzZuv6cPIeI2p0XqnIcL4VrIiuIDBfigB69vfOx5R4qJsjK3O2Fc4VU7XSUUd+dBx2l4IXfvek0HI0HFpKM9euDZFLX+0OS66LDbLv3CIe8ZD5zjPabrqw5hZZX5yJLOU99cckQujAY4sOR3Fns3pokySTWsKgcg8GyhhKt66U/Gd29fwcE0S6TE68QWpSUVHRdaMT1SZo1i8CHRtzatDLb8cDuIVuTyIlBL8nMfRWyiRp8gWhVLyrTPc8Sy5NHKC/bfUJw+GMzrxK7TVbT9R7M5bO0/v0SwyivAsLDXOgUquNeeMiRSUK9leASkXkEbSp1EXMxhhtybOmBBanP+ZNjCM5JO+cP6grXGEFSz73nkCxndzqoE1eyXbN9yYqCtoR574fJMwS9Aj2B/pMj5sdsquCBdQCdJNI6J20LEYToL7WjCmctG9XVI/h8K/Dl4or/AtKB8u2ZB2rxHCntfkO1XolmkPAOQ/0K5K/XPD44hNPkeCCFLAhmnACTIect7JMgtyN+gkdwSiOIdLkz7QEecta34IaCOh88gRu775o5j4="
  gem: gobstones-code-runner
  on:
    tags: true
    repo: gobstones/gobstones-code-runner
